# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aecd243397922570965b4f43619e7505b45c2a8c3795adbaec9bc00e0df4203a0dedb9a5eb8879786f5c426f3ba74dee233d9494324504dd2ccacd0ea1eefb4a

test:
  secret_key_base: 1d093cb869a567a0b2d43cecdaff5d0d64a590d2a28676d65f9a4f68bc154f7284934934decf828122e80dfd65d6911235dcdca4f99b608a327d123b333eb4ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
